###Delta table

In [0]:
#importing modules
from pyspark.sql import SparkSession
from delta.tables import*

In [0]:
#creating delta tables
Dd = DeltaTable.create(spark) \
    .tableName('employe_demo') \
    .addColumn('emp_id','INT') \
    .addColumn('emp_Name','STRING') \
    .addColumn('gender','STRING') \
    .addColumn('salary','INT') \
    .addColumn('dept','STRING') \
    .property('description','table created for demo purpose') \
    .location('/FileStore/table/delta/createtable1') \
    .execute()

In [0]:
%sql
select * from default.employe_demo;

In [0]:
from delta.tables import *
DeltaTable.createIfNotExists(spark) \
    .tableName('employe_demo1') \
    .addColumn('emp_id','INT') \
    .addColumn('emp_name','STRING') \
    .addColumn('gender','STRING') \
    .addColumn('salary','INT') \
    .addColumn('dep','STRING') \
    .execute()

Out[49]: <delta.tables.DeltaTable at 0x7f7b0598fd60>

In [0]:
from delta.tables import *
DeltaTable.createOrReplace(spark) \
    .tableName('employe_demo1') \
    .addColumn('emp_id','INT') \
    .addColumn('emp_name','STRING') \
    .addColumn('gender','STRING') \
    .addColumn('salary','INT') \
    .addColumn('dep','STRING') \
    .execute()

Out[50]: <delta.tables.DeltaTable at 0x7f7b04dda6d0>

In [0]:
%sql
CREATE TABLE employe_demo2(
  emp_id INT,
  emp_Name STRING,
  gender STRING,
  salary INT,
  dept STRING
  )USING DELTA

In [0]:
%sql
create table if not exists employe_demo2(
  emp_id INT,
  emp_Name STRING,
  gender STRING,
  salary INT,
  dept STRING
  )using delta

In [0]:
%sql
create or replace table employe_demo2(
  emp_id INT,
  emp_Name STRING,
  gender STRING,
  salary INT,
  dept STRING
  )using delta
  location 'dbfs:/user/hive/warehouse/employe_demo2'

---------------------------------------------------------------------------
AnalysisException                         Traceback (most recent call last)
<command-3584576722385194> in <cell line: 1>()
      5     display(df)
      6     return df
----> 7   _sqldf = ____databricks_percent_sql()
      8 finally:
      9   del ____databricks_percent_sql

<command-3584576722385194> in ____databricks_percent_sql()
      2   def ____databricks_percent_sql():
      3     import base64
----> 4     df = spark.sql(base64.standard_b64decode("Y3JlYXRlIG9yIHJlcGxhY2UgdGFibGUgZW1wbG95ZV9kZW1vKAogIGVtcF9pZCBJTlQsCiAgZW1wX05hbWUgU1RSSU5HLAogIGdlbmRlciBTVFJJTkcsCiAgc2FsYXJ5IElOVCwKICBkZXB0IFNUUklORwogICl1c2luZyBkZWx0YQogIGxvY2F0aW9uICdkYmZzOi91c2VyL2hpdmUvd2FyZWhvdXNlL2VtcGxveWVfZGVtbzIn").decode())
      5     display(df)
      6     return df

/databricks/spark/python/pyspark/instrumentation_utils.py in wrapper(*args, **kwargs)
     46             start = time.perf_counter()
     47             try:
---> 48                 res = func(*args, **kwargs)
     49                 logger.log_success(
     50                     module_name, class_name, function_name, time.perf_counter() - start, signature

/databricks/spark/python/pyspark/sql/session.py in sql(self, sqlQuery, **kwargs)
   1117             sqlQuery = formatter.format(sqlQuery, **kwargs)
   1118         try:
-> 1119             return DataFrame(self._jsparkSession.sql(sqlQuery), self)
   1120         finally:
   1121             if len(kwargs) > 0:

/databricks/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1319
   1320         answer = self.gateway_client.send_command(command)
-> 1321         return_value = get_return_value(
   1322             answer, self.gateway_client, self.target_id, self.name)
   1323

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    200                 # Hide where the exception came from that shows a non-Pythonic
    201                 # JVM exception message.
--> 202                 raise converted from None
    203             else:
    204                 raise

AnalysisException: The location of the existing table `spark_catalog`.`default`.`employe_demo` is `dbfs:/FileStore/table/delta/createtable2`. It doesn't match the specified location `dbfs:/user/hive/warehouse/employe_demo2`.

In [0]:
#creating  dataframe and using df to create delta_table
employe_data = [(100,'shiva','M',2000,'IT('),
                (200,'sai','M',8000,'HR'),
                (300,'charan','M',6000,'sales')]
employe_schema = ['emp_id','emp_name','gender','salary','dept']

df = spark.createDataFrame(data=employe_data,schema = employe_schema)

display(df)

In [0]:
df.write.format('delta').saveAsTable('default.employe_demo3')